# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_auto_20191020_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pro_id',
            new_name='profile_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
