# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20191020_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='screen1',
            new_name='screenshot',
        ),
        migrations.RemoveField(
            model_name='project',
            name='screen2',
        ),
    ]
