# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_auto_20191021_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='screenshot',
        ),
    ]
